# Generated by Django 4.1.5 on 2023-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="taskCompleted",
            field=models.BooleanField(
                default=False, help_text="Отметка о выполнении задачи"
            ),
        ),
    ]
