# Generated by Django 4.1.5 on 2023-01-29 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0002_todolist_taskcompleted"),
    ]

    operations = [
        migrations.RemoveField(model_name="todolist", name="taskDescription",),
        migrations.AddField(
            model_name="todolist",
            name="taskCompleteTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 29, 16, 25, 35, 907516),
                help_text="Время завершения задачи",
            ),
        ),
        migrations.AddField(
            model_name="todolist",
            name="taskCreatedTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 29, 16, 25, 35, 907504),
                help_text="Время создания задачи",
            ),
        ),
    ]
