# Generated by Django 4.1.5 on 2023-01-29 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0004_alter_todolist_taskcompletetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="taskCompleteTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 29, 16, 38, 11, 451415, tzinfo=datetime.timezone.utc
                ),
                help_text="Время завершения задачи",
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="taskCreatedTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 29, 16, 38, 11, 451250, tzinfo=datetime.timezone.utc
                ),
                help_text="Время создания задачи",
            ),
        ),
    ]
