# Generated by Django 4.1.5 on 2023-01-31 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0007_alter_todolist_taskcompletetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="taskCreatedTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 31, 7, 48, 0, 378389, tzinfo=datetime.timezone.utc
                ),
                help_text="Время создания задачи",
            ),
        ),
    ]
