# Generated by Django 4.1.5 on 2023-01-31 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0008_alter_todolist_taskcreatedtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="taskCompleteTime",
            field=models.DateTimeField(
                default=None, help_text="Время завершения задачи", null=True
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="taskCreatedTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 31, 8, 14, 13, 125182, tzinfo=datetime.timezone.utc
                ),
                help_text="Время создания задачи",
            ),
        ),
    ]
