# Generated by Django 4.1.5 on 2023-01-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0010_todolist_user_alter_todolist_taskcreatedtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="taskCompleteTime",
            field=models.DateTimeField(help_text="Время завершения задачи", null=True),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="taskCreatedTime",
            field=models.DateTimeField(
                auto_now=True, help_text="Время создания задачи"
            ),
        ),
    ]
