# Generated by Django 4.1.5 on 2023-01-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0011_alter_todolist_taskcompletetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="taskCompleteTime",
            field=models.DateTimeField(
                blank=True, default=None, help_text="Время завершения задачи", null=True
            ),
        ),
    ]
